---
- name: CONFIGURE LOGIN BANNER
  hosts: reserved
  gather_facts: false
  connection: local
  become: yes
  become_method: enable

  tasks:
  - name: Update login banner
    ios_banner:
      banner: login
      text: |
        ----------------------------------------
        |
        | Welcome João Pedro
        |
        ----------------------------------------
        |
        | You are logged into {{ inventory_hostname }}
        | 
        ----------------------------------------
      state: present