---
- name: CREATE LOOPBACK INTERFACE
  hosts: reserved  
  gather_facts: False  
  connection: local 
  become: yes
  become_method: enable

  tasks:
    # Loopback IPv4    
    - name: Creating loopback IPv4
      ios_interface:
        name: Loopback1
        enabled: True 
        description: Loopback interface 1 IPv4 
    
    - name: Assign IP to loopback
      ios_l3_interface: 
        name: Loopback1
        ipv4: 10.0.6.25/32 
    
    # Loopback IPv6 1
    - name: Creating first loopback IPv6
      ios_interface:
        name: Loopback2
        enabled: True 
        description: Loopback interface 1 IPv6 
    
    - name: Assign IP to loopback
      ios_l3_interface: 
        name: Loopback2
        ipv6: 2001:db8::2/128

    # Loopback IPv6 2
    - name: Creating second loopback IPv6
      ios_interface:
        name: Loopback3
        enabled: True 
        description: Loopback interface 2 IPv6 
    
    - name: Assign IP to loopback
      ios_l3_interface: 
        name: Loopback3
        ipv6: 2001:db8::3/128 